---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: votestore-pvc
  namespace: vote
spec:
  accessModes:
    - Read
  volumeMode: Filesystem
  resources:
    requests:
      storage: 400Mi
